/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAssistantRouteImport } from './routes/app/assistant'
import { Route as AppCommunityRouteImport } from './routes/app/community'
import { Route as AppCommuteRouteImport } from './routes/app/commute'
import { Route as AppContactsRouteImport } from './routes/app/contacts'
import { Route as AppDefenceRouteImport } from './routes/app/defence'
import { Route as AppFakecallRouteImport } from './routes/app/fakecall'
import { Route as AppHeatmapRouteImport } from './routes/app/heatmap'
import { Route as AppInspireRouteImport } from './routes/app/inspire'
import { Route as AppLegalRouteImport } from './routes/app/legal'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppRideRouteImport } from './routes/app/ride'
import { Route as AppSaferouteRouteImport } from './routes/app/saferoute'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSosRouteImport } from './routes/app/sos'
import { Route as AppTrackingRouteImport } from './routes/app/tracking'
import { Route as AppVaultRouteImport } from './routes/app/vault'
import { Route as AppVoiceRouteImport } from './routes/app/voice'
import { Route as GuardianDashboardRouteImport } from './routes/guardian/dashboard'
import { Route as GuardianLoginRouteImport } from './routes/guardian/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/app/assistant',
  path: '/app/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/app/community',
  path: '/app/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommuteRoute = AppCommuteRouteImport.update({
  id: '/app/commute',
  path: '/app/commute',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/app/contacts',
  path: '/app/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDefenceRoute = AppDefenceRouteImport.update({
  id: '/app/defence',
  path: '/app/defence',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFakecallRoute = AppFakecallRouteImport.update({
  id: '/app/fakecall',
  path: '/app/fakecall',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHeatmapRoute = AppHeatmapRouteImport.update({
  id: '/app/heatmap',
  path: '/app/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInspireRoute = AppInspireRouteImport.update({
  id: '/app/inspire',
  path: '/app/inspire',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLegalRoute = AppLegalRouteImport.update({
  id: '/app/legal',
  path: '/app/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/app/notifications',
  path: '/app/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRideRoute = AppRideRouteImport.update({
  id: '/app/ride',
  path: '/app/ride',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSaferouteRoute = AppSaferouteRouteImport.update({
  id: '/app/saferoute',
  path: '/app/saferoute',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSosRoute = AppSosRouteImport.update({
  id: '/app/sos',
  path: '/app/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/app/tracking',
  path: '/app/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/app/vault',
  path: '/app/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/app/voice',
  path: '/app/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianDashboardRoute = GuardianDashboardRouteImport.update({
  id: '/guardian/dashboard',
  path: '/guardian/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianLoginRoute = GuardianLoginRouteImport.update({
  id: '/guardian/login',
  path: '/guardian/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/community': typeof AppCommunityRoute
  '/app/commute': typeof AppCommuteRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/defence': typeof AppDefenceRoute
  '/app/fakecall': typeof AppFakecallRoute
  '/app/heatmap': typeof AppHeatmapRoute
  '/app/inspire': typeof AppInspireRoute
  '/app/legal': typeof AppLegalRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/ride': typeof AppRideRoute
  '/app/saferoute': typeof AppSaferouteRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sos': typeof AppSosRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/vault': typeof AppVaultRoute
  '/app/voice': typeof AppVoiceRoute
  '/guardian/dashboard': typeof GuardianDashboardRoute
  '/guardian/login': typeof GuardianLoginRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/community': typeof AppCommunityRoute
  '/app/commute': typeof AppCommuteRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/defence': typeof AppDefenceRoute
  '/app/fakecall': typeof AppFakecallRoute
  '/app/heatmap': typeof AppHeatmapRoute
  '/app/inspire': typeof AppInspireRoute
  '/app/legal': typeof AppLegalRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/ride': typeof AppRideRoute
  '/app/saferoute': typeof AppSaferouteRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sos': typeof AppSosRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/vault': typeof AppVaultRoute
  '/app/voice': typeof AppVoiceRoute
  '/guardian/dashboard': typeof GuardianDashboardRoute
  '/guardian/login': typeof GuardianLoginRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/community': typeof AppCommunityRoute
  '/app/commute': typeof AppCommuteRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/defence': typeof AppDefenceRoute
  '/app/fakecall': typeof AppFakecallRoute
  '/app/heatmap': typeof AppHeatmapRoute
  '/app/inspire': typeof AppInspireRoute
  '/app/legal': typeof AppLegalRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/ride': typeof AppRideRoute
  '/app/saferoute': typeof AppSaferouteRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sos': typeof AppSosRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/vault': typeof AppVaultRoute
  '/app/voice': typeof AppVoiceRoute
  '/guardian/dashboard': typeof GuardianDashboardRoute
  '/guardian/login': typeof GuardianLoginRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/app/assistant'
    | '/app/community'
    | '/app/commute'
    | '/app/contacts'
    | '/app/defence'
    | '/app/fakecall'
    | '/app/heatmap'
    | '/app/inspire'
    | '/app/legal'
    | '/app/notifications'
    | '/app/profile'
    | '/app/ride'
    | '/app/saferoute'
    | '/app/settings'
    | '/app/sos'
    | '/app/tracking'
    | '/app/vault'
    | '/app/voice'
    | '/guardian/dashboard'
    | '/guardian/login'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/app/assistant'
    | '/app/community'
    | '/app/commute'
    | '/app/contacts'
    | '/app/defence'
    | '/app/fakecall'
    | '/app/heatmap'
    | '/app/inspire'
    | '/app/legal'
    | '/app/notifications'
    | '/app/profile'
    | '/app/ride'
    | '/app/saferoute'
    | '/app/settings'
    | '/app/sos'
    | '/app/tracking'
    | '/app/vault'
    | '/app/voice'
    | '/guardian/dashboard'
    | '/guardian/login'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/login'
    | '/app/assistant'
    | '/app/community'
    | '/app/commute'
    | '/app/contacts'
    | '/app/defence'
    | '/app/fakecall'
    | '/app/heatmap'
    | '/app/inspire'
    | '/app/legal'
    | '/app/notifications'
    | '/app/profile'
    | '/app/ride'
    | '/app/saferoute'
    | '/app/settings'
    | '/app/sos'
    | '/app/tracking'
    | '/app/vault'
    | '/app/voice'
    | '/guardian/dashboard'
    | '/guardian/login'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppCommuteRoute: typeof AppCommuteRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDefenceRoute: typeof AppDefenceRoute
  AppFakecallRoute: typeof AppFakecallRoute
  AppHeatmapRoute: typeof AppHeatmapRoute
  AppInspireRoute: typeof AppInspireRoute
  AppLegalRoute: typeof AppLegalRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRideRoute: typeof AppRideRoute
  AppSaferouteRoute: typeof AppSaferouteRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSosRoute: typeof AppSosRoute
  AppTrackingRoute: typeof AppTrackingRoute
  AppVaultRoute: typeof AppVaultRoute
  AppVoiceRoute: typeof AppVoiceRoute
  GuardianDashboardRoute: typeof GuardianDashboardRoute
  GuardianLoginRoute: typeof GuardianLoginRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/app/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/community': {
      id: '/app/community'
      path: '/app/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/commute': {
      id: '/app/commute'
      path: '/app/commute'
      fullPath: '/app/commute'
      preLoaderRoute: typeof AppCommuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/contacts': {
      id: '/app/contacts'
      path: '/app/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/defence': {
      id: '/app/defence'
      path: '/app/defence'
      fullPath: '/app/defence'
      preLoaderRoute: typeof AppDefenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/fakecall': {
      id: '/app/fakecall'
      path: '/app/fakecall'
      fullPath: '/app/fakecall'
      preLoaderRoute: typeof AppFakecallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/heatmap': {
      id: '/app/heatmap'
      path: '/app/heatmap'
      fullPath: '/app/heatmap'
      preLoaderRoute: typeof AppHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inspire': {
      id: '/app/inspire'
      path: '/app/inspire'
      fullPath: '/app/inspire'
      preLoaderRoute: typeof AppInspireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/legal': {
      id: '/app/legal'
      path: '/app/legal'
      fullPath: '/app/legal'
      preLoaderRoute: typeof AppLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/app/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ride': {
      id: '/app/ride'
      path: '/app/ride'
      fullPath: '/app/ride'
      preLoaderRoute: typeof AppRideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/saferoute': {
      id: '/app/saferoute'
      path: '/app/saferoute'
      fullPath: '/app/saferoute'
      preLoaderRoute: typeof AppSaferouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sos': {
      id: '/app/sos'
      path: '/app/sos'
      fullPath: '/app/sos'
      preLoaderRoute: typeof AppSosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tracking': {
      id: '/app/tracking'
      path: '/app/tracking'
      fullPath: '/app/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vault': {
      id: '/app/vault'
      path: '/app/vault'
      fullPath: '/app/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/voice': {
      id: '/app/voice'
      path: '/app/voice'
      fullPath: '/app/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/dashboard': {
      id: '/guardian/dashboard'
      path: '/guardian/dashboard'
      fullPath: '/guardian/dashboard'
      preLoaderRoute: typeof GuardianDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/login': {
      id: '/guardian/login'
      path: '/guardian/login'
      fullPath: '/guardian/login'
      preLoaderRoute: typeof GuardianLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppCommuteRoute: AppCommuteRoute,
  AppContactsRoute: AppContactsRoute,
  AppDefenceRoute: AppDefenceRoute,
  AppFakecallRoute: AppFakecallRoute,
  AppHeatmapRoute: AppHeatmapRoute,
  AppInspireRoute: AppInspireRoute,
  AppLegalRoute: AppLegalRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRideRoute: AppRideRoute,
  AppSaferouteRoute: AppSaferouteRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSosRoute: AppSosRoute,
  AppTrackingRoute: AppTrackingRoute,
  AppVaultRoute: AppVaultRoute,
  AppVoiceRoute: AppVoiceRoute,
  GuardianDashboardRoute: GuardianDashboardRoute,
  GuardianLoginRoute: GuardianLoginRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
